### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.

spring.jmx:
   enabled: false

server:
  port: 8090

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: api-todo
  version: 1.0
  description: TODO API
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
---
spring:
  profiles: default 

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE

---
spring:
  profiles: production

spring.jpa:
    hibernate.ddl-auto: update
    show-sql: false
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

spring.datasource:
  url : jdbc:mysql://localhost:3306/todo
  username: root
  password: p@ssw0rd
  testWhileIdle: true
  validationQuery: SELECT 1

logging:
  file: logs/api/todo.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.exam.todo.api.rest: INFO
    org.hibernate: WARN

---
spring:
  profiles: dev

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    
spring.jpa:
    hibernate.ddl-auto: create-drop

logging:
  file: logs/api/todo.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: INFO
    com.exam.todo.api.rest: INFO
    org.hibernate: WARN

---
spring:
  profiles: test

spring.jpa:
    hibernate.ddl-auto: create-drop

logging:
  file: logs/api/todo.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: INFO
    com.exam.todo.api.rest: INFO
    org.hibernate: INFO